# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/${EXPENSEAPP_NAME:expenseApp}?createDatabaseIfNotExist=true&userSSL=false&serverTimezone=UTC
    # Username and secret
    username:  ${DB_USERNAME:root}
    password:  ${DB_PASSWORD:password}
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle:  true
    validationQuery:  SELECT 1
  jpa:
    show-sql:  true
    hibernate:
      ddl-auto: update

      # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect


